# Numpy Arrays

In [1]:
import numpy as np

## Array Initializations

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [6]:
np.linspace(2,3,11)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])

In [7]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

## Array builtins

### Initialize some random array

In [8]:
c=np.linspace(0, 1, 5)
print(c)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
a=np.array([c, c**2, c-0.325])
print(a)

[[ 0.      0.25    0.5     0.75    1.    ]
 [ 0.      0.0625  0.25    0.5625  1.    ]
 [-0.325  -0.075   0.175   0.425   0.675 ]]


### Array sizes and shapes

In [10]:
len(a) # same as a.shape[0]


3

In [11]:
np.size(a) # total number of elements


15

In [12]:
a.shape # shape

(3, 5)

### Reductions

In [13]:
np.amin(a) # minimal value in array

-0.325

In [14]:
np.amax(a) # maximal value in array

1.0

In [15]:
a.max(axis=0) # max along specific axis of array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
a.max(1)

array([1.   , 1.   , 0.675])

In [17]:
a.mean(axis=0) # mean of array along axis

array([-0.10833333,  0.07916667,  0.30833333,  0.57916667,  0.89166667])

In [18]:
a.mean(1)

array([0.5  , 0.375, 0.175])

In [19]:
a.std(axis=0) # standard deviation

array([0.15320647, 0.13320306, 0.13894443, 0.13320306, 0.15320647])

In [20]:
a.std(1)

array([0.35355339, 0.36869703, 0.35355339])

## Accessing Elements

In [24]:
print(a, '\n')
print( "a[0]                  \t", a[0] )
print( "a[:,0]                \t", a[:,0] )
print( "a[1]                  \t", a[1] )
print( "a[:,1]                \t", a[:,1] )
print( "a[-1]                 \t", a[-1] )
print( "a[:,-1]               \t", a[:,-1] )
print( "a[a > 1.4]            \t", a[a > 1.4] )
print( "a[(a > 1) & (c < 1.3)]\t", a[(a > 1) & (c < 1.3)] )


[[ 0.      0.25    0.5     0.75    1.    ]
 [ 0.      0.0625  0.25    0.5625  1.    ]
 [-0.325  -0.075   0.175   0.425   0.675 ]] 

a[0]                  	 [0.   0.25 0.5  0.75 1.  ]
a[:,0]                	 [ 0.     0.    -0.325]
a[1]                  	 [0.     0.0625 0.25   0.5625 1.    ]
a[:,1]                	 [ 0.25    0.0625 -0.075 ]
a[-1]                 	 [-0.325 -0.075  0.175  0.425  0.675]
a[:,-1]               	 [1.    1.    0.675]
a[a > 1.4]            	 []
a[(a > 1) & (c < 1.3)]	 []
