# Matrices

In [8]:
import numpy as np

## Initialization

In [9]:
a=np.matrix([1, 5]) 
print(a)

[[1 5]]


In [10]:
b=np.matrix([2, 9, -1])
print(b)

[[ 2  9 -1]]


In [11]:
A=np.matrix([[1, 2],[7, 4]]) 
print(A)

[[1 2]
 [7 4]]


In [12]:
B=np.matrix([[1, -2, 5],[-2, 7, 3]])
print(B)

[[ 1 -2  5]
 [-2  7  3]]


In [13]:
c = np.array([-2, 3, 5])
print(c)

[-2  3  5]


## Matrix Operations


In [14]:
# matrix product
a*B

matrix([[-9, 33, 20]])

In [15]:
# transposed matrix product
B.T*a.T

matrix([[-9],
        [33],
        [20]])

In [16]:
# squaring matrix
A**2

matrix([[15, 10],
        [35, 30]])

In [20]:
# squaring matrix... 
A*A

matrix([[15, 10],
        [35, 30]])

In [19]:
# cross product
np.cross(b,c)

array([[48, -8, 24]])

In [23]:
# transpose
print(A)
print(A.T)

[[1 2]
 [7 4]]
[[1 7]
 [2 4]]


In [26]:
# invert
print(A)
print(A.I)
print(np.linalg.inv(A))

[[1 2]
 [7 4]]
[[-0.4  0.2]
 [ 0.7 -0.1]]
[[-0.4  0.2]
 [ 0.7 -0.1]]


## Solving Equations

In [21]:
Ca = np.array([[-2,1],[0.5,2]])
da = np.array([[-3],[5]])
Cm = np.matrix([[-2,1],[0.5,2]])
dm = np.matrix([[-3],[5]])

In [27]:
# SOLVING C * x = d -> C^-1 * d = x
Cm.I*dm

matrix([[2.44444444],
        [1.88888889]])

In [28]:
np.dot(np.linalg.inv(Ca),da)

array([[2.44444444],
       [1.88888889]])

## Determinants and Norm

In [29]:
np.linalg.det(Cm)

-4.5

In [31]:
np.linalg.det(np.eye(4))

1.0

In [33]:
np.linalg.det(np.ones((4,4)))

0.0

In [35]:
print(np.linalg.norm(A), np.linalg.norm(B), np.linalg.norm(Cm))

8.366600265340756 9.591663046625438 3.0413812651491097
